package nu.xell.util.math;

/**
 * A probability distribution in mathematical statistics.
 * 
 * @author Tobias Axell
 */
public interface ProbabilityDistribution {
	
	/**
	 * The expected value, E[X], of a stochastic variable X 
	 * distributed over this distribution.
	 * 
	 * @return The expected value of a stochastic variable distributed
	 * 			over this distribution.
	 */
	public double expectedValue();
	
	/**
	 * The variance of stochastic variables over this distribution.
	 * 
	 * @return The variance of this distribution.
	 */
	public double variance();
	
	/**
	 * The probability density function for the distribution.
	 * 
	 * @param x The value to calculate the probability density of.
	 * @return The probability density of parameter 'x'.
	 */
	public double probabilityDensityOf(double x);
	
	/**
	 * The cumulative density function for the distribution.
	 * 
	 * @param x The value to calculate the cumulative density of.
	 * @return The cumulative density of parameter 'x'.
	 */
	public double cumulativeDensityOf(double x);
	
	/**
	 * Generates random values distributed over this probability 
	 * distribution. <br/><br/>
	 * 
	 * If the probability distribution <strong>is a discrete probability 
	 * distribution</strong> then every value generated by this method must
	 * be an integer i.e. <br/><br/>
	 * 
	 * &nbsp;&nbsp;&nbsp;&nbsp;<code>v == Math.round(v)</code><br/><br/>
	 * 
	 * must hold for all values of <b>v</b> generated by this method.
	 * 
	 * @return A random value distributed over this distribution.
	 */
	public double nextRandom();
}
